chatbot/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("room/", views.chatroom, name="chatbot_room"),
]

main/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:id>/", views.post_detail, name="post_detail"),
    path(_("post/new/"), views.post_edit, name="post_create"),
    path(_("post/<int:pk>/"), views.post_edit, name="post_update"),
    path(_("search/"), views.search_post, name="search_post"),
    path(_("delete/<int:pk>/"), views.post_delete, name="post_delete"),
]

multilang_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path("chatbot/", include("chatbot.urls", namespace="chatbot")),
    path("", include("main.urls", namespace="blog")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chatbot/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Post(models.Model):
    """
    Blog posts model
    """

    title = models.CharField(_("title"), max_length=250)
    content = models.TextField(_("content"))
    publication_date = models.DateTimeField(default=timezone.now)

    # model field arguments:
    #       auto_now_add => the date will be saved automatically when creating an object
    #       auto_now     => the date will be updated automatically when saving an object
    # author field creates a relationship between users and posts, that will help indicate
    # which user wrote which posts
    #
    # related_name helps to specify the name of the reverse relationships from User to Post.
    # using (user.blog_posts) notation to access related objects
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post_image = models.ImageField(_("photo"),
                                   upload_to="post_images/", blank=True, null=True)

    # Meta class defines metadata for the model
    #
    # Ordering attribute sorts result by publication_date in descending order, with hypen
    # before field name
    #
    # Index on (publication_date and title) will help improve performance for queries
    # filtering or ordering results by these fields
    class Meta:
        ordering = ["-publication_date"]
        indexes = [
            models.Index(fields=["-publication_date", "title"]),
        ]

    # returns a string with human readable representation of the object
    def __str__(self):
        return str(self.title)

    # get_absolute_url() returns the canonical URL for the object
    # reverse() function builds the URL dynamically using the URL name defined
    # in the URL patterns
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id])

main/forms.py
from django import forms
from .models import Post

SEARCH_BY_CHOICES = (
    ("title", "Title"),
    ("content", "Content")
)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "post_image"]


class SearchForm(forms.Form):
    search = forms.CharField(required=False, min_length=3)
    search_by = forms.ChoiceField(
        required=False,
        choices=SEARCH_BY_CHOICES
    )

chatbot/views.py
from django.shortcuts import render

# Create your views here.


def chatroom(request):
    return render(request, "chat/chatroom.html")

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from PIL import Image
from io import BytesIO
from django.core.files.images import ImageFile
from django.contrib import messages
from django.utils import timezone
from .models import Post
from .forms import PostForm, SearchForm

# Create your views here.


def post_list(request):
    post_list = Post.objects.all()

    # paginator with 10 posts per page
    paginator = Paginator(post_list, 6)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, "blog/post/list.html", {"posts": posts})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    latest_posts = Post.objects.order_by(
        "-publication_date").exclude(id=post.id)[:5]
    return render(request, "blog/post/detail.html",
                  {"post": post,
                   "latest_posts": latest_posts,
                   })


def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post:
        post.delete()
        messages.success(request,
                         f"Post {post} deleted successfully")
    else:
        messages.success(request,
                         f"No Post with id {post.pk} found")
    return redirect("blog:post_list")


def post_edit(request, pk=None):
    if pk is not None:
        post = get_object_or_404(Post, pk=pk)
    else:
        post = None

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            updated_post = form.save(commit=False)
            updated_post.author = request.user
            updated_post.content = form.cleaned_data["content"]
            updated_post.updated = timezone.now()

            post_image = form.cleaned_data.get("post_image")
            if post_image and not hasattr(post_image, "path"):
                image = Image.open(post_image)
                image.thumbnail((500, 500))
                image_data = BytesIO()
                image.save(fp=image_data, format=post_image.image.format)
                image_file = ImageFile(image_data)
                updated_post.post_image.save(post_image.name, image_file)
            updated_post.save()

            if post is None:
                messages.success(request,
                                 f"Post {updated_post} created successfully")
            else:
                messages.success(request,
                                 f"Post {updated_post} updated successfully")

            return redirect("blog:post_detail", updated_post.pk)
    form = PostForm(instance=post)

    return render(
        request, "blog/post/create_edit_post.html", {
            "form": form,
            "instance": post,
            "is_file_upload": True}
    )


def search_post(request):
    search_text = request.GET.get("search", "")
    form = SearchForm(request.GET)
    posts = set()

    if form.is_valid() and form.cleaned_data["search"]:
        search = form.cleaned_data["search"]
        search_by = form.cleaned_data.get("search_by") or "title"
        if search_by == "title":
            posts = Post.objects.filter(title__icontains=search)
        else:
            posts = Post.objects.filter(content__icontains=search)
    else:
        form = SearchForm()

    return render(request,
                  "search/search-results.html", {
                      "form": form,
                      "search_text": search_text,
                      "posts": posts
                  })

templates/alert_toast.html
{% load i18n %}
<div class="alert alert-{%if message.level_tag == 'error'%}danger{% else %}{{message.level_tag}}{% endif %} alert-dismissible"
    role="alert">
    <h4 class="alert-heading">{{message.level_tag|title}}</h4>
    <hr />
    <div>{{message}}</div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css"
        rel="stylesheet" />
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" />
</head>

<body>
    <div class="container-fluid">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}

        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:post_list'%}">{% trans "My Blog" %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav  mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list'%}">
                                {% trans "View all posts" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:post_create' %}">
                                {% trans "Create new post" %}
                            </a>
                        </li>
                    </ul>

                    <form action="{% url 'blog:search_post' %}" class="d-flex">
                        <input class="form-control form-control-lg mx-2" type="search" placeholder="Search"
                            aria-label="Search" name="search" value="{{ search_text }}" minlength="3"
                            style="width:30rem;" />
                        <button class="btn btn-outline-success" type="submit">{% trans "Search" %}</button>
                    </form>

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                {% trans "Language" %}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for language in languages %}
                                <li>
                                    <a href="/{{ language.code }}/" {%if language.code is LANGUAGE_CODE %}
                                        class="selected" {%endif%} class="dropdown-item">
                                        {{ language.name_local }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-bot">
            <div class="fab-container">
                <a class="nav-link" href="{% url 'chat:chatbot_room'%}" style="text-decoration: none; color: #fff">
                    <i class="fa-solid fa-headset"></i>
                </a>
            </div>
        </div>

        <!-- The main block for content. All templates that extend the base template
        should add content to this block -->
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

        <!--  object context are passed with json_sscript template filter within this block tag
        to securely use the value of objects with javascript -->
        {% block include_js %}
        {% endblock %}

        <script>
            document.addEventListener('DOMContentLoaded', (event) => {
                /* Allows the execution of javascript code when the Document Object Model(DOM)
                has finished loading */
                //DOM loaded
                {% block domready %}
                {% endblock %}
            })
        </script>

        <!-- Bootstrap Javascript Bundle -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    </div>
</body>

</html>

templates/blog/post/create_edit_post.html
{% extends "../../base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Create or Edit Post" %}{% endblock %}

{% block content %}
{% for message in messages %}
{% include "../../alert_toast.html" with message=message %}
{% endfor %}


{% if instance %}
{% blocktrans with instance_title=instance.title %}
<h3 class="text-center">Edit post with title {{ instance_title }}</h3>
{% endblocktrans %}
{% else %}
<h3 class="text-center">{% trans "Create post" %}</h3>
{% endif %}

<div class="container">
    <form method="post" {% if is_file_upload %}enctype="multipart/form-data" {% endif %}>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mb-3">
            {% if instance %}
            {% trans "Edit Post" %}
            {% else %}
            {% trans "Create Post" %}
            {% endif %}
        </button>
    </form>
</div>
{% endblock %}

templates/blog/post/detail.html
{% extends "../../base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
{% blocktrans with title=post.title %}
{{ title }}
{% endblocktrans %}
{% endblock %}

{% block content %}
{% for message in messages %}
{% include "../../alert_toast.html" with message=message %}
{% endfor %}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h1>
                {% blocktrans with title=post.title %}
                {{ title }}
                {% endblocktrans %}
            </h1>
            <p class="date">
                {% blocktrans with publication_date=post.publication_date author=post.author %}
                Published {{ publication_date }} by {{ author }}
                {% endblocktrans %}
            </p>
            <img src="{% if post.post_image %}{{ post.post_image.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}"
                style="width:50rem;height:25rem;" />
            <p>
                {% blocktrans with user_post_content_detail=post.content|linebreaks %}
                {{ user_post_content_detail }}
                {% endblocktrans %}
            </p>
            <a class="btn btn-primary mb-3" href="{% url 'blog:post_update' post.pk %}" role="button">
                {% trans "Edit"%}
            </a>
            <a class="btn btn-primary mb-3" href="{% url 'blog:post_delete' post.pk %}" role="button">
                {% trans "Delete"%}
            </a>
        </div>
        <div class="col-md-3">
            <h4>{% trans "Recent posts" %}</h4>
            {% for post in latest_posts %}
            <ul>
                <li>
                    <a href="{{ post.get_absolute_url }}">
                        {% blocktrans with post_title=post.title %}
                        {{post_title}}
                        {% endblocktrans %}
                    </a>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/blog/post/list.html
{% extends "../../base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Blog post articles" %}{% endblock %}
{% block content %}

{% for message in messages %}
{% include "../../alert_toast.html" with message=message %}
{% endfor %}

<div class="container">
    <div class="row gy-5">
        {% for post in posts %}
        <div class="col-4 justify-content-around">
            <div class="card h-100" style="width: 18rem;">
                <img src="{% if post.post_image %}{{ post.post_image.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}"
                    class="card-img-top" alt="no image for post" style="height: 12rem;" />

                <div class="card-body">
                    <h5 class="card-title">
                        {% blocktrans with title=post.title %}
                        {{title }}
                        {% endblocktrans %}
                    </h5>

                    <p class="card-text">
                        {% blocktrans with user_post_content=post.content|truncatewords:30|linebreaks %}
                        {{ user_post_content }}
                        {% endblocktrans %}
                    </p>

                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary mb-2 text-center">
                        {% trans "Read full article" %}
                    </a>
                </div>

                <div class="card-footer text-muted">
                    {% blocktrans with publication_date=post.publication_date author=post.author%}
                    Published {{ publication_date }} by {{ author }}
                    {% endblocktrans %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% include "../../pagination.html" with page=posts %}
{% endblock %}

templates/chat/chatroom.html
{% extends "../base.html" %}
{% load i18n %}
{% block title %}{% trans "Chat room" %}{% endblock %}
{% block content %}

<div class="chatpane"></div>
<div class="chat-input d-grid gap-3 position-absolute" style="width: 98%; top: 30rem;">
    <input id="chat-message-input" type="text" class="form-control" placeholder="your message to bot"
        aria-label="your message to bot" aria-describedby="addon-wrapping">
    <button id="chat-message-submit" type="submit" class="btn btn-primary">Send</button>
</div>
{% endblock %}

<!--the code is rendered as <script id="request-user" type="application/json">username</script>
this value can then be retrieved in the domready block by parsing the content with
id="request-user" using JSON.parse(). This is a safeway to use Python objects in javascript
-->
{% block include_js %}
{{ request.user.username|json_script:"request-user" }}
{% endblock %}

{% block domready %}
const requestUser = JSON.parse(
document.getElementById('request-user').textContent
)

const url = 'ws://' + window.location.host + '/ws/chatbot/room/'
const chatSocket = new WebSocket(url)

chatSocket.onmessage = (event) => {
const data = JSON.parse(event.data)
const chat = document.querySelector(".chatpane")
const source = 'other'
const name = 'GPT-bot'

chat.innerHTML += '<div class="message ' + source + '">' +
    '<strong>' + name + '</strong><br>' +
    data.message + '</div>';
chat.scrollTop = chat.scrollHeight;
}

chatSocket.onclose = (event) => {
console.error('Chat socket closed unexpectedly')
}

//sending message to the WebSocket
const input = document.getElementById('chat-message-input')
const submitButton = document.getElementById('chat-message-submit')

submitButton.addEventListener('click', (event) => {
const message = input.value
console.log("clicked")

if(message){
const chat = document.querySelector(".chatpane")
const source = 'me'
const name = 'Me'

chat.innerHTML += '<div class="message ' + source + '">' +
    '<strong>' + name + '</strong><br>' +
    message + '</div>';
chat.scrollTop = chat.scrollHeight;


//send message in JSON format
chatSocket.send(JSON.stringify({
'message': message
}))

//clear input
input.value = '';
input.focus();

}
})

if (input){
input.addEventListener('keypress', (event) => {
if(event.key === 'Enter'){
//cancel the default action, if needed
event.preventDefault();
//trigger click event on button
console.log("input field clicked on enter")
submitButton.click();
}
});
input.focus();
}


{% endblock %}

templates/pagination.html
{% load i18n %}
<nav aria-label="Page navigation" class="my-3">
    <ul class="pagination pagination-lg justify-content-center">
        <li class="page-item">
            {% if page.has_previous %}
            <a class="page-link" href="?page={{ page.previous_page_number }}">
                {% trans "Previous" %}
            </a>
            {% endif %}
        </li>

        <li class="page-item">
            {% blocktrans with page_number=page.number total_pages=page.paginator.num_pages %}
            <a class="page-link">Page {{ page_number }} of {{ total_pages }}</a>
            {% endblocktrans %}
        </li>

        <li class="page-item">
            {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">{% trans "Next" %}</a>
            {% endif %}
        </li>
    </ul>
</nav>

templates/search/search-results.html
{% extends "../base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Post search" %}{% endblock %}
{% block content %}

<div class="container">
    <h2 class="text-center">{% trans "Search for Posts" %}</h2>
    <form>
        {{ form|crispy }}
        <button class="btn btn-primary mb-3" type="submit">{% trans "Search" %}</button>
    </form>
    {% if form.is_valid and search_text %}
    <h3>{% trans "Search results for" %} <em>{{ search_text }}</em></h3>

    <ul class="list-group list-group-flush">
        {% for post in posts %}
        <li class="list-group-item">
            <a href="{{ post.get_absolute_url }}">
                {% blocktrans with title=post.title %}
                {{title }}
                {% endblocktrans %}
            </a>
        </li>
        {% empty %}
        {% trans "No search results found for" %} {{search_text}}
        {% endfor %}
    </ul>
    {% endif %}
    {% endblock %}
</div>